name: GitHub Build Actions To Build a Branch Specific Snapshot

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      BUILD_EVENT: ${{ github.event_name }}
      BRANCH_SNAPSHOT: ${{ github.ref_name }}
      REF_NAME: ${{ github.ref_name }}
      OSSRH_USERNAME: ${{ secrets.OSSRH_USERNAME }}
      OSSRH_PASSWORD: ${{ secrets.OSSRH_TOKEN }}
      SIGNING_KEY_ID: ${{ secrets.SIGNING_KEY_ID }}
      SIGNING_KEY: ${{ secrets.SIGNING_KEY }}
      SIGNING_PASSWORD: ${{ secrets.SIGNING_PASSWORD }}
      COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
      GODEBUG: x509sha1=1
    steps:
      - name: Test
        run: |
          echo BSF 9 ${{ env.BRANCH_SNAPSHOT }}
      - name: Check out code
        uses: actions/checkout@v2
      - name: Build and Test
        run: chmod +x gradlew && ./gradlew clean

